# Generated by Django 3.2.3 on 2021-05-28 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_student_gender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='academic',
            old_name='degree_board',
            new_name='degree_university',
        ),
        migrations.AddField(
            model_name='student',
            name='mother_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='mother_occupation',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
