# Generated by Django 3.2.3 on 2021-05-31 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_rename_academic_id_student_academic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='profile_photo',
            field=models.ImageField(default='students/profile_photos/profile.png', null=True, upload_to='students/profile_photos/'),
        ),
    ]
